### ISSUE TITLE
SOW: Write Up Question Type

### ISSUE THREAD

**Issue by jillpe** [notch8/viva#176]
## Summary
[History Question Samples](https://docs.google.com/document/d/1Ix5gNa3cspocVGUyLBE0p9tc70No5OVWjrd-Qq1sYos/edit)
VIVA would like 'Write Up's to be a question type that is available for their users.

<details><summary>Example1</summary>
Answer the following questions for your pop culture source. Include parenthetical citations in your answers when you paraphrase or quote ideas and information from the readings or the pop culture source (treat it like a primary source text). Cite the pop culture source as: (Title). Cite the assigned readings as: (“Title of Article”).

You may do outside research and use reviews or cultural analyses to inform your annotation if you wish -- it is not necessary or required. If you do use external sources, please include a full citation of the source at the top or bottom of your write-up and include parenthetical citations following the format above when referencing ideas or information in your responses.

Title of the Pop Culture Source, Author (Director if film or tv show), Publisher (executive producers if film or tv show and production company), Date Created. 
Who is the audience for the Pop Culture Source? Include specific details from the source to support your answer. 
Which ancient civilization(s) does the Pop Culture Source reference? Be as specific as possible about dynasty, time period, etc.
List the main people, objects, and actions included or mentioned in the Pop Culture Source from the ancient civilization(s) listed above. 
Discuss 2 things the Pop Culture Source does well in representing the ancient civilization. Include specific examples from the Pop Culture Source and use relevant assigned readings from the course to support your answers. Each point should be a complete paragraph at minimum.   
If you could change one thing about the Pop Culture Source’s treatment of the ancient civilization to improve its historical accuracy without changing the entire premise of the piece (unless the entire premise is problematic in some way), what would it be and why? Include specific example(s) from the Pop Culture Source and use the assigned readings to support your suggestion.

</details>

<details><summary>Example 2 - individual assignment, multiple files required for submission</summary>
**Overview**
This Lab will focus on 2 fundamental skills that historians must be able to do: **sequence information** (a then b then c) and cite where we found our information.
Sequencing information (artifact metadata, events, etc.) within a chronology is an important skill, because it helps one understand how things sit in relation to one another. Thanks to the internet, we can lookup dates (or approximate dates) and critically evaluate sources to understand the credibility of the dates. But putting artifacts and events in sequence can help surface change and continuity over time: what trends, events, and ideas occur is shaped by the historical period, or when they happen. 
We cite others' work for 2 main reasons. The first is to give appropriate honest credit to those whose work and ideas we include in our own scholarship. Academia has [a long way to go](https://www.insidehighered.com/news/2018/08/16/new-research-shows-extent-gender-gap-citations) when it comes to equitable recognition and citation practices, but we will do our part by being open and thorough about citing others’ ideas and work in this assignment and throughout the semester! The second reason to cite is that it’s how we can enter the “scholarly conversation” with respect and surety. Citing research is one way to demonstrate your own credibility -- to avoid being that person who is just being loud in the comment section on the internet. 
**Do:**
Make a copy of the [Timeline Template](https://docs.google.com/spreadsheets/d/1VJN4V5ibESCDj5lFTsOTW9ernOLBXoYZ-Rl9KIMLKuI/edit?usp=sharing) spreadsheet for yourself to work on. Important Note: Don't change the column headers, don't remove any columns, and don't leave any blank rows in your spreadsheet!  
Pay close attention to the columns that are required: A (year), J (headline), K (description), M (media caption). See the template spreadsheet for what to enter in each column. Start entering your timeline info in Row 3.  
From this week’s readings on the development of religious beliefs around the ancient world, choose 6 specific events, people, ideas, or artifacts to create your own timeline of key points in religious development in the ancient world. There are many more than 6 key points across all the assigned readings! You will carefully select 6 specific events, people, ideas, or artifacts and sequencing them in order from oldest to most recent. 
Explore the [Ancient and Medieval History Database](https://online-infobase-com.ndcproxy.mnpals.net/HRC/Browse/PrimarySources/7) primary sources. Choose 2 primary sources that are most relevant to your 6 points. Use the Citation feature at the top of the primary source page (just below the source’s title) to get the full-citation in Chicago Manual of Style format.
Write-up: write a short paragraph explaining your 6 key points and 2 primary source selections: what threads them together and what is important about these 6 points in history together. Include the full citation in Chicago Manual of Style format of the 2 primary sources at the end of your write-up. 

**Turn in 2 files:**
1. **Your timeline spreadsheet with 6 complete entries in .CSV or .XLSX or .ODS or Google Sheets formats**. Only these formats will be accepted -- you will not receive points for this part of the assignment if you turn in the spreadsheet in a different file format. If you have questions about how to make sure you save/export the file the correct way, please ask!
2. Write-up (explanation paragraph and primary source citations) as a Word doc, PDF, Google Doc, or LibreOffice file.
</details>

<details><summary>Example 3</summary>
Florentine Codex
Link to [Codex](https://www.loc.gov/resource/gdcwdl.wdl_10621/?sp=254) and [Assessment](https://drive.google.com/file/d/14VnYsR8XOdD0mwuIIVdJFARtpC4KPKQe/view?usp=sharing)
</details>

<details><summary>Example 4</summary>
Opposition to the Philippine-American War
Link to [Assessment](https://drive.google.com/file/d/1XMj9ABQ9i_-eVwHnS6Hzserp0lZIZRvE/view?usp=sharing)
</details>

## Tasks
- [ ] Backend is set up for Write Up question types for example 1
- [ ] Backend is set up for Write Up question types for example 2
- [ ] Backend is set up for Write Up question types for example 3
- [ ] Backend is set up for Write Up question types for example 4
- [ ] UI is set up for Write Up question types for example 1
- [ ] UI is set up for Write Up question types for example 2
- [ ] UI is set up for Write Up question types for example 3
- [ ] UI is set up for Write Up question types for example 4
