### ISSUE TITLE
Categorization Question Type Backend Set Up

### ISSUE THREAD

**Issue by jillpe** [notch8/viva#177]
## Summary
[History Question Samples](https://docs.google.com/document/d/1Ix5gNa3cspocVGUyLBE0p9tc70No5OVWjrd-Qq1sYos/edit)

VIVA would like Matching/Categorization questions to be available for their users. 

<details><summary>Example 1</summary>
Match the map projection with the year it was created: 

Projection Names:
Mercator
Stereographic
Robinson

Dates:
1963
1569
Before 150CE

</details>

<details><summary>Example 2</summary>
Arrange these Chinese dynasties into chronological order from oldest to most recent:

Qin
Han
Shang
Ming
Yuan

</details>

<details><summary>Example 3</summary>
Match the philosopher with their religion or philosophical tradition:

Marcus Aurelius
Averroes
A’ishah al-Ba’uniyyah
Thomas Aquinas

Islam
Stoicism
Sufism
Catholicism

</details>

<details><summary>Example 4</summary>
Categorize each artwork with the era in which it was created: 

Eras:
Archaic
Classical
Hellenistic

Artworks:
[Nike (Winged Victory) of Samothrace](https://smarthistory.org/nike-winged-victory-of-samothrace/)

[Nike Adjusting Her Sandal](https://smarthistory.org/nike-adjusting-her-sandal-temple-of-athena-nike-acropolis-athens/), Temple of Athena Nike

 
[The Erechtheion](https://smarthistory.org/the-erechtheion/), Athens

[The Kouroi of Kleobis and Biton](https://smarthistory.org/kleobis-and-biton/)
</details>

## Tasks
- [ ] Backend is set up for Categorization question types for example 1, 3, 4 (they are the same)
- [ ]  Backend is set up for Categorization question types for example 2

## Acceptance Criteria
- [ ] As a user, I can upload Categorization questions via a csv and they are imported into the correct model
