### ISSUE TITLE
UI Form Wireframe

### ISSUE THREAD

**Issue by jillpe** [notch8/viva#273]
## Summary
VIVA would like the ability to create a question through the UI, rather than having their users create CSV's for their questions. Their users will likely not be doing batch uploads, so they like that the UI uploads one question at a time. 

The actual front-end and back-end set up of the form will come in a later phase of work. The goal of this ticket is to create a wireframe for the Form.

This feature is very similar to the hyku/hyrax 'Add new Work' through the UI feature. We will probably want to base this form off of [that one](https://demo.hyku-demo.notch8.cloud/concern/generic_works/new?locale=en). 

![Image](https://github.com/user-attachments/assets/b772554e-d87c-470b-9ec8-28b048cc10ca)

- [Sample Homework Questions](https://drive.google.com/drive/folders/1GNY23qGIviu56W_jyzk58v37btMGU_PV)

## Tasks
- [ ] Create a question
- [ ] Question: essay
- [ ] Question: Mult choice & SATA
- [ ] Question: Matching
- [ ] Question: Drag and Drop
- [ ] Question: Bowtie
- [ ] Question: Categorization
- [ ] Question: True False
- [ ] Question: Case study

## Acceptance Criteria
- [ ] Form wireframes have been approved by the client
